/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feko_steffensmeierdoty;

import javax.swing.JButton;

/**
 *
 * @author rms130
 */
public class CharacterModGUI extends javax.swing.JFrame {

    private JButton[] teamSlots = new JButton[4];
    
    /**
     * Creates new form CharacterModGUI
     */
    public CharacterModGUI() {
        initComponents();
        initEditTeamSlots();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainContainer = new javax.swing.JLayeredPane();
        MenuButtonLayer = new javax.swing.JLayeredPane();
        BattleButton = new javax.swing.JButton();
        AlliesButton = new javax.swing.JButton();
        MiscButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        BottomBorder = new javax.swing.JLabel();
        MainStatsLayer = new javax.swing.JLayeredPane();
        TopBorder = new javax.swing.JLabel();
        AlliesLayer = new javax.swing.JLayeredPane();
        EditStatsLayer = new javax.swing.JLayeredPane();
        CharacterPortrait = new javax.swing.JLabel();
        NamePlateText = new javax.swing.JLabel();
        NamePlate = new javax.swing.JLabel();
        StatsInterface = new javax.swing.JLabel();
        TopBorderStats = new javax.swing.JLabel();
        AlliesOptionsLayer = new javax.swing.JLayeredPane();
        LearnSkillsText = new javax.swing.JLabel();
        EquipSkillsText = new javax.swing.JLabel();
        EditTeamsText = new javax.swing.JLabel();
        AlliesBannerText = new javax.swing.JLabel();
        AlliesBanner = new javax.swing.JButton();
        EquipSkillsButton = new javax.swing.JButton();
        LearnSkillsButton = new javax.swing.JButton();
        EditTeamsButton = new javax.swing.JButton();
        AlliesOptionsBackground = new javax.swing.JLabel();
        EditTeamsLayer = new javax.swing.JLayeredPane();
        TeamLoadout = new javax.swing.JLayeredPane();
        Slot1 = new javax.swing.JButton();
        Slot2 = new javax.swing.JButton();
        Slot3 = new javax.swing.JButton();
        Slot4 = new javax.swing.JButton();
        UndoText = new javax.swing.JLabel();
        UndoButton = new javax.swing.JButton();
        CharacterButton3 = new javax.swing.JButton();
        CharacterButton2 = new javax.swing.JButton();
        CharacterButton1 = new javax.swing.JButton();
        TeamPickerUI = new javax.swing.JLabel();
        TeamLoadoutUI = new javax.swing.JLabel();
        EditTeamsBackButton = new javax.swing.JButton();
        EditTeamsBannerText = new javax.swing.JLabel();
        EditTeamBanner = new javax.swing.JButton();
        EditTeamsBackground = new javax.swing.JLabel();
        HomeLayer = new javax.swing.JLayeredPane();
        Stone = new javax.swing.JLabel();
        NewsBoard = new javax.swing.JLabel();
        Fountain = new javax.swing.JLabel();
        Owl = new javax.swing.JLabel();
        Character1 = new javax.swing.JLabel();
        Character2 = new javax.swing.JLabel();
        Character3 = new javax.swing.JLabel();
        Character4 = new javax.swing.JLabel();
        CastleBackground = new javax.swing.JLabel();
        BattleLayer = new javax.swing.JLayeredPane();
        StoryMapsText = new javax.swing.JLabel();
        StoryMapsButton = new javax.swing.JButton();
        StoryMapsPNG = new javax.swing.JLabel();
        WorldMapBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 925));
        setMinimumSize(new java.awt.Dimension(540, 925));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(540, 925));

        MainContainer.setMaximumSize(new java.awt.Dimension(540, 925));
        MainContainer.setMinimumSize(new java.awt.Dimension(540, 925));
        MainContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuButtonLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BattleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/battle_button_idle.png"))); // NOI18N
        BattleButton.setBorderPainted(false);
        BattleButton.setContentAreaFilled(false);
        BattleButton.setFocusPainted(false);
        BattleButton.setMaximumSize(new java.awt.Dimension(90, 90));
        BattleButton.setMinimumSize(new java.awt.Dimension(90, 90));
        BattleButton.setPreferredSize(new java.awt.Dimension(90, 90));
        BattleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BattleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BattleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BattleButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BattleButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BattleButtonMouseReleased(evt);
            }
        });
        BattleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BattleButtonActionPerformed(evt);
            }
        });
        MenuButtonLayer.add(BattleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, 100));

        AlliesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_button_idle.png"))); // NOI18N
        AlliesButton.setBorderPainted(false);
        AlliesButton.setContentAreaFilled(false);
        AlliesButton.setFocusPainted(false);
        AlliesButton.setMaximumSize(new java.awt.Dimension(90, 90));
        AlliesButton.setMinimumSize(new java.awt.Dimension(90, 90));
        AlliesButton.setPreferredSize(new java.awt.Dimension(90, 90));
        AlliesButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                AlliesButtonMouseDragged(evt);
            }
        });
        AlliesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlliesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlliesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlliesButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AlliesButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AlliesButtonMouseReleased(evt);
            }
        });
        AlliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlliesButtonActionPerformed(evt);
            }
        });
        MenuButtonLayer.add(AlliesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 100));

        MiscButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/misc_button_idle.png"))); // NOI18N
        MiscButton.setBorderPainted(false);
        MiscButton.setContentAreaFilled(false);
        MiscButton.setFocusPainted(false);
        MiscButton.setMaximumSize(new java.awt.Dimension(90, 90));
        MiscButton.setMinimumSize(new java.awt.Dimension(90, 90));
        MiscButton.setPreferredSize(new java.awt.Dimension(90, 90));
        MiscButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiscButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MiscButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MiscButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MiscButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MiscButtonMouseReleased(evt);
            }
        });
        MenuButtonLayer.add(MiscButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 90, 100));

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/home_button_idle.png"))); // NOI18N
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setFocusPainted(false);
        HomeButton.setMaximumSize(new java.awt.Dimension(90, 90));
        HomeButton.setMinimumSize(new java.awt.Dimension(90, 90));
        HomeButton.setPreferredSize(new java.awt.Dimension(90, 90));
        HomeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HomeButtonMouseDragged(evt);
            }
        });
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HomeButtonMouseReleased(evt);
            }
        });
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        MenuButtonLayer.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 100));

        BottomBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/char_mod_border_bottom.png"))); // NOI18N
        MenuButtonLayer.add(BottomBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 180));

        MainContainer.add(MenuButtonLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 540, 130));

        MainStatsLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/char_mod_border_top.png"))); // NOI18N
        MainStatsLayer.add(TopBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainContainer.add(MainStatsLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 80));

        AlliesLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AlliesLayer.setVisible(false);

        EditStatsLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        EditStatsLayer.add(CharacterPortrait, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        NamePlateText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NamePlateText.setForeground(new java.awt.Color(255, 255, 255));
        NamePlateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamePlateText.setFocusable(false);
        NamePlateText.setRequestFocusEnabled(false);
        EditStatsLayer.add(NamePlateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, 30));

        NamePlate.setForeground(new java.awt.Color(255, 255, 255));
        NamePlate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamePlate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/name_plate.png"))); // NOI18N
        EditStatsLayer.add(NamePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        StatsInterface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/stats_border.png"))); // NOI18N
        EditStatsLayer.add(StatsInterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        TopBorderStats.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TopBorderStats.setForeground(new java.awt.Color(255, 255, 255));
        TopBorderStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/top_border_stats.png"))); // NOI18N
        EditStatsLayer.add(TopBorderStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        AlliesLayer.add(EditStatsLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 120));
        EditStatsLayer.setVisible(false);

        AlliesOptionsLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LearnSkillsText.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        LearnSkillsText.setForeground(new java.awt.Color(255, 255, 255));
        LearnSkillsText.setText("Learn Skills");
        AlliesOptionsLayer.add(LearnSkillsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 200, 60));

        EquipSkillsText.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        EquipSkillsText.setForeground(new java.awt.Color(255, 255, 255));
        EquipSkillsText.setText("Equip Skills");
        AlliesOptionsLayer.add(EquipSkillsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 200, 60));

        EditTeamsText.setFont(new java.awt.Font("Franklin Gothic Book", 1, 30)); // NOI18N
        EditTeamsText.setForeground(new java.awt.Color(255, 255, 255));
        EditTeamsText.setText("Edit Teams");
        AlliesOptionsLayer.add(EditTeamsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 60));

        AlliesBannerText.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        AlliesBannerText.setForeground(new java.awt.Color(51, 51, 51));
        AlliesBannerText.setText("Allies");
        AlliesOptionsLayer.add(AlliesBannerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 110, 60));

        AlliesBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/tan_header.png"))); // NOI18N
        AlliesBanner.setBorderPainted(false);
        AlliesBanner.setContentAreaFilled(false);
        AlliesBanner.setFocusPainted(false);
        AlliesBanner.setMaximumSize(new java.awt.Dimension(90, 90));
        AlliesBanner.setMinimumSize(new java.awt.Dimension(90, 90));
        AlliesBanner.setPreferredSize(new java.awt.Dimension(90, 90));
        AlliesOptionsLayer.add(AlliesBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 500, 100));

        EquipSkillsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_idle.png"))); // NOI18N
        EquipSkillsButton.setBorderPainted(false);
        EquipSkillsButton.setContentAreaFilled(false);
        EquipSkillsButton.setFocusPainted(false);
        EquipSkillsButton.setMaximumSize(new java.awt.Dimension(90, 90));
        EquipSkillsButton.setMinimumSize(new java.awt.Dimension(90, 90));
        EquipSkillsButton.setPreferredSize(new java.awt.Dimension(90, 90));
        EquipSkillsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                EquipSkillsButtonMouseDragged(evt);
            }
        });
        EquipSkillsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EquipSkillsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EquipSkillsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EquipSkillsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EquipSkillsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EquipSkillsButtonMouseReleased(evt);
            }
        });
        EquipSkillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipSkillsButtonActionPerformed(evt);
            }
        });
        AlliesOptionsLayer.add(EquipSkillsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 460, 100));

        LearnSkillsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_idle.png"))); // NOI18N
        LearnSkillsButton.setBorderPainted(false);
        LearnSkillsButton.setContentAreaFilled(false);
        LearnSkillsButton.setFocusPainted(false);
        LearnSkillsButton.setMaximumSize(new java.awt.Dimension(90, 90));
        LearnSkillsButton.setMinimumSize(new java.awt.Dimension(90, 90));
        LearnSkillsButton.setPreferredSize(new java.awt.Dimension(90, 90));
        LearnSkillsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LearnSkillsButtonMouseDragged(evt);
            }
        });
        LearnSkillsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnSkillsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LearnSkillsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LearnSkillsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LearnSkillsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LearnSkillsButtonMouseReleased(evt);
            }
        });
        LearnSkillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearnSkillsButtonActionPerformed(evt);
            }
        });
        AlliesOptionsLayer.add(LearnSkillsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 460, 100));

        EditTeamsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_idle.png"))); // NOI18N
        EditTeamsButton.setBorderPainted(false);
        EditTeamsButton.setContentAreaFilled(false);
        EditTeamsButton.setFocusPainted(false);
        EditTeamsButton.setMaximumSize(new java.awt.Dimension(90, 90));
        EditTeamsButton.setMinimumSize(new java.awt.Dimension(90, 90));
        EditTeamsButton.setPreferredSize(new java.awt.Dimension(90, 90));
        EditTeamsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                EditTeamsButtonMouseDragged(evt);
            }
        });
        EditTeamsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditTeamsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditTeamsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditTeamsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditTeamsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EditTeamsButtonMouseReleased(evt);
            }
        });
        EditTeamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTeamsButtonActionPerformed(evt);
            }
        });
        AlliesOptionsLayer.add(EditTeamsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 460, 100));

        AlliesOptionsBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/allies_background.png"))); // NOI18N
        AlliesOptionsLayer.add(AlliesOptionsBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 30, 630, 930));

        AlliesLayer.add(AlliesOptionsLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 900));

        EditTeamsLayer.setMinimumSize(new java.awt.Dimension(540, 900));
        EditTeamsLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TeamLoadout.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        Slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png"))); // NOI18N
        Slot1.setBorder(null);
        Slot1.setContentAreaFilled(false);
        TeamLoadout.add(Slot1);

        Slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png"))); // NOI18N
        Slot2.setBorder(null);
        Slot2.setContentAreaFilled(false);
        TeamLoadout.add(Slot2);

        Slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png"))); // NOI18N
        Slot3.setBorder(null);
        Slot3.setContentAreaFilled(false);
        TeamLoadout.add(Slot3);

        Slot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png"))); // NOI18N
        Slot4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Slot4.setContentAreaFilled(false);
        TeamLoadout.add(Slot4);

        EditTeamsLayer.add(TeamLoadout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 390, 90));

        UndoText.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        UndoText.setForeground(new java.awt.Color(255, 255, 255));
        UndoText.setText("Undo");
        UndoText.setVisible(false);
        EditTeamsLayer.add(UndoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 370, 60, 30));

        UndoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png"))); // NOI18N
        UndoButton.setBorderPainted(false);
        UndoButton.setContentAreaFilled(false);
        UndoButton.setFocusPainted(false);
        UndoButton.setMaximumSize(new java.awt.Dimension(90, 90));
        UndoButton.setMinimumSize(new java.awt.Dimension(90, 90));
        UndoButton.setPreferredSize(new java.awt.Dimension(90, 90));
        UndoButton.setVisible(false);
        UndoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UndoButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UndoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UndoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UndoButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                UndoButtonMouseReleased(evt);
            }
        });
        UndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoButtonActionPerformed(evt);
            }
        });
        EditTeamsLayer.add(UndoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 90));

        CharacterButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/soleil_silver_portrait_idle.png"))); // NOI18N
        CharacterButton3.setBorderPainted(false);
        CharacterButton3.setContentAreaFilled(false);
        CharacterButton3.setFocusPainted(false);
        CharacterButton3.setMaximumSize(new java.awt.Dimension(90, 90));
        CharacterButton3.setMinimumSize(new java.awt.Dimension(90, 90));
        CharacterButton3.setPreferredSize(new java.awt.Dimension(90, 90));
        CharacterButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CharacterButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CharacterButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CharacterButton3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CharacterButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CharacterButton3MouseReleased(evt);
            }
        });
        CharacterButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharacterButton3ActionPerformed(evt);
            }
        });
        EditTeamsLayer.add(CharacterButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, 90));

        CharacterButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/alfonse_silver_portrait_idle.png"))); // NOI18N
        CharacterButton2.setBorderPainted(false);
        CharacterButton2.setContentAreaFilled(false);
        CharacterButton2.setFocusPainted(false);
        CharacterButton2.setMaximumSize(new java.awt.Dimension(90, 90));
        CharacterButton2.setMinimumSize(new java.awt.Dimension(90, 90));
        CharacterButton2.setPreferredSize(new java.awt.Dimension(90, 90));
        CharacterButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CharacterButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CharacterButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CharacterButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CharacterButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CharacterButton2MouseReleased(evt);
            }
        });
        CharacterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharacterButton2ActionPerformed(evt);
            }
        });
        EditTeamsLayer.add(CharacterButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, 90));

        CharacterButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/anna_silver_portrait_idle.png"))); // NOI18N
        CharacterButton1.setBorderPainted(false);
        CharacterButton1.setContentAreaFilled(false);
        CharacterButton1.setFocusPainted(false);
        CharacterButton1.setMaximumSize(new java.awt.Dimension(90, 90));
        CharacterButton1.setMinimumSize(new java.awt.Dimension(90, 90));
        CharacterButton1.setPreferredSize(new java.awt.Dimension(90, 90));
        CharacterButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CharacterButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CharacterButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CharacterButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CharacterButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CharacterButton1MouseReleased(evt);
            }
        });
        CharacterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharacterButton1ActionPerformed(evt);
            }
        });
        EditTeamsLayer.add(CharacterButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, 90));

        TeamPickerUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/team_picker_UI.png"))); // NOI18N
        EditTeamsLayer.add(TeamPickerUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 600, 400));

        TeamLoadoutUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/team_loadout_UI.png"))); // NOI18N
        EditTeamsLayer.add(TeamLoadoutUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 540, 170));

        EditTeamsBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/back_button_idle.png"))); // NOI18N
        EditTeamsBackButton.setBorderPainted(false);
        EditTeamsBackButton.setContentAreaFilled(false);
        EditTeamsBackButton.setFocusPainted(false);
        EditTeamsBackButton.setMaximumSize(new java.awt.Dimension(90, 90));
        EditTeamsBackButton.setMinimumSize(new java.awt.Dimension(90, 90));
        EditTeamsBackButton.setPreferredSize(new java.awt.Dimension(90, 90));
        EditTeamsBackButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                EditTeamsBackButtonMouseDragged(evt);
            }
        });
        EditTeamsBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditTeamsBackButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditTeamsBackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditTeamsBackButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditTeamsBackButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EditTeamsBackButtonMouseReleased(evt);
            }
        });
        EditTeamsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTeamsBackButtonActionPerformed(evt);
            }
        });
        EditTeamsLayer.add(EditTeamsBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 100));

        EditTeamsBannerText.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        EditTeamsBannerText.setForeground(new java.awt.Color(51, 51, 51));
        EditTeamsBannerText.setText("Edit Teams");
        EditTeamsLayer.add(EditTeamsBannerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 210, 60));

        EditTeamBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/tan_header.png"))); // NOI18N
        EditTeamBanner.setBorderPainted(false);
        EditTeamBanner.setContentAreaFilled(false);
        EditTeamBanner.setFocusPainted(false);
        EditTeamBanner.setMaximumSize(new java.awt.Dimension(90, 90));
        EditTeamBanner.setMinimumSize(new java.awt.Dimension(90, 90));
        EditTeamBanner.setPreferredSize(new java.awt.Dimension(90, 90));
        EditTeamsLayer.add(EditTeamBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 500, 80));

        EditTeamsBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/allies_background.png"))); // NOI18N
        EditTeamsLayer.add(EditTeamsBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -30, 630, 930));

        AlliesLayer.add(EditTeamsLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 540, 900));

        MainContainer.add(AlliesLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 930));

        HomeLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/glowing_stone.png"))); // NOI18N
        HomeLayer.add(Stone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));

        NewsBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/news_board.png"))); // NOI18N
        HomeLayer.add(NewsBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        Fountain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/fountain.png"))); // NOI18N
        HomeLayer.add(Fountain, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, -1));

        Owl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/owl.png"))); // NOI18N
        HomeLayer.add(Owl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        Character1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/characters/anna.png"))); // NOI18N
        HomeLayer.add(Character1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));
        HomeLayer.add(Character2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));
        HomeLayer.add(Character3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));
        HomeLayer.add(Character4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));

        CastleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/player_castle_background.png"))); // NOI18N
        HomeLayer.add(CastleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 630, 930));

        MainContainer.add(HomeLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 930));

        BattleLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BattleLayer.setVisible(false);

        StoryMapsText.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        StoryMapsText.setForeground(new java.awt.Color(51, 51, 51));
        StoryMapsText.setText("Story Maps");
        BattleLayer.add(StoryMapsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 130, 40));

        StoryMapsButton.setBorderPainted(false);
        StoryMapsButton.setContentAreaFilled(false);
        StoryMapsButton.setFocusPainted(false);
        StoryMapsButton.setMaximumSize(new java.awt.Dimension(90, 90));
        StoryMapsButton.setMinimumSize(new java.awt.Dimension(90, 90));
        StoryMapsButton.setPreferredSize(new java.awt.Dimension(90, 90));
        StoryMapsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                StoryMapsButtonMouseDragged(evt);
            }
        });
        StoryMapsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StoryMapsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StoryMapsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StoryMapsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StoryMapsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StoryMapsButtonMouseReleased(evt);
            }
        });
        StoryMapsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoryMapsButtonActionPerformed(evt);
            }
        });
        BattleLayer.add(StoryMapsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, 170));

        StoryMapsPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/main_story_button_idle.png"))); // NOI18N
        BattleLayer.add(StoryMapsPNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        WorldMapBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/world_map.png"))); // NOI18N
        BattleLayer.add(WorldMapBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 630, 930));

        MainContainer.add(BattleLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MiscButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiscButtonMouseEntered
        MiscButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/misc_button_hover.png")));
    }//GEN-LAST:event_MiscButtonMouseEntered

    private void MiscButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiscButtonMouseExited
        MiscButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/misc_button_idle.png")));
    }//GEN-LAST:event_MiscButtonMouseExited

    private void MiscButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiscButtonMouseClicked
        
    }//GEN-LAST:event_MiscButtonMouseClicked

    private void MiscButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiscButtonMousePressed
        MiscButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/misc_button_click.png")));
    }//GEN-LAST:event_MiscButtonMousePressed

    private void BattleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BattleButtonMouseClicked
        HomeLayer.setVisible(false);
        AlliesLayer.setVisible(false);
        EditStatsLayer.setVisible(false);
        AlliesOptionsLayer.setVisible(true);
        MainStatsLayer.setVisible(true);
        BattleLayer.setVisible(true);
    }//GEN-LAST:event_BattleButtonMouseClicked

    private void BattleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BattleButtonMouseEntered
        BattleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/battle_button_hover.png")));
    }//GEN-LAST:event_BattleButtonMouseEntered

    private void BattleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BattleButtonMouseExited
        BattleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/battle_button_idle.png")));
    }//GEN-LAST:event_BattleButtonMouseExited

    private void BattleButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BattleButtonMousePressed
        BattleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/battle_button_click.png")));
    }//GEN-LAST:event_BattleButtonMousePressed

    private void AlliesButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlliesButtonMouseDragged
        
    }//GEN-LAST:event_AlliesButtonMouseDragged

    private void AlliesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlliesButtonMouseClicked
        BattleLayer.setVisible(false);
        HomeLayer.setVisible(false);
        EditStatsLayer.setVisible(false);
        AlliesOptionsLayer.setVisible(true);
        MainStatsLayer.setVisible(true);
        AlliesLayer.setVisible(true);
    }//GEN-LAST:event_AlliesButtonMouseClicked

    private void AlliesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlliesButtonMouseEntered
        AlliesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_button_hover.png")));
    }//GEN-LAST:event_AlliesButtonMouseEntered

    private void AlliesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlliesButtonMouseExited
        AlliesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_button_idle.png")));
    }//GEN-LAST:event_AlliesButtonMouseExited

    private void AlliesButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlliesButtonMousePressed
        AlliesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_button_click.png")));
    }//GEN-LAST:event_AlliesButtonMousePressed

    private void MiscButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiscButtonMouseReleased
        MiscButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/misc_button_hover.png")));
    }//GEN-LAST:event_MiscButtonMouseReleased

    private void AlliesButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlliesButtonMouseReleased
        AlliesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_button_hover.png")));
    }//GEN-LAST:event_AlliesButtonMouseReleased

    private void BattleButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BattleButtonMouseReleased
        BattleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/battle_button_hover.png")));
    }//GEN-LAST:event_BattleButtonMouseReleased

    private void HomeButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMouseDragged

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        BattleLayer.setVisible(false);
        AlliesLayer.setVisible(false);
        EditStatsLayer.setVisible(false);
        AlliesOptionsLayer.setVisible(true);
        MainStatsLayer.setVisible(true);
        HomeLayer.setVisible(true);
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void HomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseEntered
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/home_button_hover.png")));
    }//GEN-LAST:event_HomeButtonMouseEntered

    private void HomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseExited
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/home_button_idle.png")));
    }//GEN-LAST:event_HomeButtonMouseExited

    private void HomeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMousePressed
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/home_button_click.png")));
    }//GEN-LAST:event_HomeButtonMousePressed

    private void HomeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseReleased
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/home_button_idle.png")));
    }//GEN-LAST:event_HomeButtonMouseReleased

    private void BattleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BattleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BattleButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void StoryMapsButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoryMapsButtonMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_StoryMapsButtonMouseDragged

    private void StoryMapsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoryMapsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StoryMapsButtonMouseClicked

    private void StoryMapsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoryMapsButtonMouseEntered
        StoryMapsPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/main_story_button_hover.png")));
    }//GEN-LAST:event_StoryMapsButtonMouseEntered

    private void StoryMapsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoryMapsButtonMouseExited
        StoryMapsPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/main_story_button_idle.png")));
    }//GEN-LAST:event_StoryMapsButtonMouseExited

    private void StoryMapsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoryMapsButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_StoryMapsButtonMousePressed

    private void StoryMapsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoryMapsButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_StoryMapsButtonMouseReleased

    private void StoryMapsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoryMapsButtonActionPerformed
        MapGUI mapGUI = new MapGUI();
        mapGUI.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_StoryMapsButtonActionPerformed

    private void AlliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlliesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlliesButtonActionPerformed

    private void EditTeamsButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsButtonMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsButtonMouseDragged

    private void EditTeamsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsButtonMouseClicked
        MainStatsLayer.setVisible(false);
        AlliesOptionsLayer.setVisible(false);
        EditStatsLayer.setVisible(true);
        EditTeamsLayer.setVisible(true);
    }//GEN-LAST:event_EditTeamsButtonMouseClicked

    private void EditTeamsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsButtonMouseEntered
        EditTeamsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_hover.png")));
    }//GEN-LAST:event_EditTeamsButtonMouseEntered

    private void EditTeamsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsButtonMouseExited
        EditTeamsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_idle.png")));
    }//GEN-LAST:event_EditTeamsButtonMouseExited

    private void EditTeamsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsButtonMousePressed

    private void EditTeamsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsButtonMouseReleased

    private void EditTeamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTeamsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsButtonActionPerformed

    private void LearnSkillsButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnSkillsButtonMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_LearnSkillsButtonMouseDragged

    private void LearnSkillsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnSkillsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LearnSkillsButtonMouseClicked

    private void LearnSkillsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnSkillsButtonMouseEntered
        LearnSkillsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_hover.png")));
    }//GEN-LAST:event_LearnSkillsButtonMouseEntered

    private void LearnSkillsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnSkillsButtonMouseExited
        LearnSkillsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_idle.png")));
    }//GEN-LAST:event_LearnSkillsButtonMouseExited

    private void LearnSkillsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnSkillsButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LearnSkillsButtonMousePressed

    private void LearnSkillsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnSkillsButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_LearnSkillsButtonMouseReleased

    private void LearnSkillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearnSkillsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LearnSkillsButtonActionPerformed

    private void EquipSkillsButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipSkillsButtonMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipSkillsButtonMouseDragged

    private void EquipSkillsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipSkillsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipSkillsButtonMouseClicked

    private void EquipSkillsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipSkillsButtonMouseEntered
        EquipSkillsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_hover.png")));
    }//GEN-LAST:event_EquipSkillsButtonMouseEntered

    private void EquipSkillsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipSkillsButtonMouseExited
        EquipSkillsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/allies_option_button_idle.png")));
    }//GEN-LAST:event_EquipSkillsButtonMouseExited

    private void EquipSkillsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipSkillsButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipSkillsButtonMousePressed

    private void EquipSkillsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipSkillsButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipSkillsButtonMouseReleased

    private void EquipSkillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipSkillsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipSkillsButtonActionPerformed

    private void EditTeamsBackButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsBackButtonMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsBackButtonMouseDragged

    private void EditTeamsBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsBackButtonMouseClicked
        EditTeamsLayer.setVisible(false);
        EditStatsLayer.setVisible(false);
        AlliesOptionsLayer.setVisible(true);
        MainStatsLayer.setVisible(true);
    }//GEN-LAST:event_EditTeamsBackButtonMouseClicked

    private void EditTeamsBackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsBackButtonMouseEntered
        EditTeamsBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/back_button_hover.png")));
    }//GEN-LAST:event_EditTeamsBackButtonMouseEntered

    private void EditTeamsBackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsBackButtonMouseExited
        EditTeamsBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/back_button_idle.png")));
    }//GEN-LAST:event_EditTeamsBackButtonMouseExited

    private void EditTeamsBackButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsBackButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsBackButtonMousePressed

    private void EditTeamsBackButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTeamsBackButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsBackButtonMouseReleased

    private void EditTeamsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTeamsBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTeamsBackButtonActionPerformed

    private void CharacterButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton1MouseClicked
        editTeamLoadout(CharacterButton1,"/img/portraits/anna_silver_portrait_idle.png","/img/portraits/anna_silver_portrait_clicked.png");
    }//GEN-LAST:event_CharacterButton1MouseClicked

    private void CharacterButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton1MouseEntered

    private void CharacterButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton1MouseExited

    private void CharacterButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton1MousePressed

    private void CharacterButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton1MouseReleased

    private void CharacterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharacterButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton1ActionPerformed

    private void CharacterButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton2MouseClicked
        editTeamLoadout(CharacterButton2,"/img/portraits/alfonse_silver_portrait_idle.png","/img/portraits/alfonse_silver_portrait_clicked.png");
    }//GEN-LAST:event_CharacterButton2MouseClicked

    private void CharacterButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton2MouseEntered

    private void CharacterButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton2MouseExited

    private void CharacterButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton2MousePressed

    private void CharacterButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton2MouseReleased

    private void CharacterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharacterButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton2ActionPerformed

    private void CharacterButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton3MouseClicked

    private void CharacterButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton3MouseEntered

    private void CharacterButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton3MouseExited

    private void CharacterButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton3MousePressed
        editTeamLoadout(CharacterButton3,"/img/portraits/soleil_silver_portrait_idle.png","/img/portraits/soleil_silver_portrait_clicked.png");
    }//GEN-LAST:event_CharacterButton3MousePressed

    private void CharacterButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CharacterButton3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton3MouseReleased

    private void CharacterButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharacterButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharacterButton3ActionPerformed

    private void UndoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UndoButtonMouseClicked
        for(int i = 1; i < teamSlots.length+1; i++){
            if(i==4 && !teamSlots[i].getIcon().toString().equals(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png")).toString())){
                teamSlots[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png")));
                return;
            }
                
            if(teamSlots[i].getIcon().toString().equals(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png")).toString())) {
                teamSlots[i-1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png")));
                return;
            }
        }
    }//GEN-LAST:event_UndoButtonMouseClicked

    private void UndoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UndoButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoButtonMouseEntered

    private void UndoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UndoButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoButtonMouseExited

    private void UndoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UndoButtonMousePressed
        // TODO add your handling code here:    `````````````
    }//GEN-LAST:event_UndoButtonMousePressed

    private void UndoButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UndoButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoButtonMouseReleased

    private void UndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoButtonActionPerformed

    private void editTeamLoadout(JButton characterButton, String idleImg, String clickImg) {
        if(characterButton.getIcon().toString().equals(new javax.swing.ImageIcon(getClass().getResource(clickImg)).toString())){
            characterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(idleImg)));

            for(int i = 0; i < teamSlots.length; i++){
                if(teamSlots[i].getIcon().toString().equals(new javax.swing.ImageIcon(getClass().getResource(idleImg)).toString())) {
                    while(i < teamSlots.length-1){
                        teamSlots[i].setIcon(teamSlots[i+1].getIcon());
                        i++;
                    }
                    return;
                }
            }
        } else {
            characterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(clickImg)));
            for(JButton jb: teamSlots){
                if(jb.getIcon().toString().equals(new javax.swing.ImageIcon(getClass().getResource("/img/portraits/empty_portrait.png")).toString())) {
                    jb.setIcon(new javax.swing.ImageIcon(getClass().getResource(idleImg)));
                    return;
                }
            }
        }
    }
    
    private void initEditTeamSlots() {
        teamSlots[0] = Slot1;
        teamSlots[1] = Slot2;
        teamSlots[2] = Slot3;
        teamSlots[3] = Slot4;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterModGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterModGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterModGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterModGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterModGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlliesBanner;
    private javax.swing.JLabel AlliesBannerText;
    private javax.swing.JButton AlliesButton;
    private javax.swing.JLayeredPane AlliesLayer;
    private javax.swing.JLabel AlliesOptionsBackground;
    private javax.swing.JLayeredPane AlliesOptionsLayer;
    private javax.swing.JButton BattleButton;
    private javax.swing.JLayeredPane BattleLayer;
    private javax.swing.JLabel BottomBorder;
    private javax.swing.JLabel CastleBackground;
    private javax.swing.JLabel Character1;
    private javax.swing.JLabel Character2;
    private javax.swing.JLabel Character3;
    private javax.swing.JLabel Character4;
    private javax.swing.JButton CharacterButton1;
    private javax.swing.JButton CharacterButton2;
    private javax.swing.JButton CharacterButton3;
    private javax.swing.JLabel CharacterPortrait;
    private javax.swing.JLayeredPane EditStatsLayer;
    private javax.swing.JButton EditTeamBanner;
    private javax.swing.JButton EditTeamsBackButton;
    private javax.swing.JLabel EditTeamsBackground;
    private javax.swing.JLabel EditTeamsBannerText;
    private javax.swing.JButton EditTeamsButton;
    private javax.swing.JLayeredPane EditTeamsLayer;
    private javax.swing.JLabel EditTeamsText;
    private javax.swing.JButton EquipSkillsButton;
    private javax.swing.JLabel EquipSkillsText;
    private javax.swing.JLabel Fountain;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLayeredPane HomeLayer;
    private javax.swing.JButton LearnSkillsButton;
    private javax.swing.JLabel LearnSkillsText;
    private javax.swing.JLayeredPane MainContainer;
    private javax.swing.JLayeredPane MainStatsLayer;
    private javax.swing.JLayeredPane MenuButtonLayer;
    private javax.swing.JButton MiscButton;
    private javax.swing.JLabel NamePlate;
    private javax.swing.JLabel NamePlateText;
    private javax.swing.JLabel NewsBoard;
    private javax.swing.JLabel Owl;
    private javax.swing.JButton Slot1;
    private javax.swing.JButton Slot2;
    private javax.swing.JButton Slot3;
    private javax.swing.JButton Slot4;
    private javax.swing.JLabel StatsInterface;
    private javax.swing.JLabel Stone;
    private javax.swing.JButton StoryMapsButton;
    private javax.swing.JLabel StoryMapsPNG;
    private javax.swing.JLabel StoryMapsText;
    private javax.swing.JLayeredPane TeamLoadout;
    private javax.swing.JLabel TeamLoadoutUI;
    private javax.swing.JLabel TeamPickerUI;
    private javax.swing.JLabel TopBorder;
    private javax.swing.JLabel TopBorderStats;
    private javax.swing.JButton UndoButton;
    private javax.swing.JLabel UndoText;
    private javax.swing.JLabel WorldMapBackground;
    // End of variables declaration//GEN-END:variables
}
