/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feko_steffensmeierdoty;

import java.util.logging.Level;
import java.util.logging.Logger;
import objects.Party;

/**
 *
 * @author Justin
 */
public class GameOverGUI extends javax.swing.JFrame {

    private CharacterModGUI cmGUI;
    
    public GameOverGUI() {
        initComponents();
        gameOverTransition();
    }
    
    public GameOverGUI(CharacterModGUI cmGUI) {
        this.cmGUI = cmGUI;
        initComponents();
        gameOverTransition();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LevelTransition = new javax.swing.JLayeredPane();
        Feather = new javax.swing.JLabel();
        GameOverText = new javax.swing.JLabel();
        GameOverBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 925));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LevelTransition.setMaximumSize(new java.awt.Dimension(540, 930));
        LevelTransition.setMinimumSize(new java.awt.Dimension(540, 930));
        LevelTransition.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Feather.setVisible(false);
        Feather.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/gameOverFeather.png"))); // NOI18N
        LevelTransition.add(Feather, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 330, 90));

        GameOverText.setVisible(false);
        GameOverText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UIMenu/gameOverText.png"))); // NOI18N
        LevelTransition.add(GameOverText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 470, 90));

        GameOverBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/gameOverBackground.png"))); // NOI18N
        GameOverBackground.setToolTipText("");
        LevelTransition.add(GameOverBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 620, 940));

        getContentPane().add(LevelTransition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gameOverTransition() {
        Thread gameOverTransitionThread = new Thread() {    
            public void run() {
                try {
                    Thread.sleep(800);
                    GameOverText.setVisible(true);
                    Thread.sleep(1500);
                    Feather.setVisible(true);
                    Thread.sleep(1750);
                    GameOverBackground.setVisible(false);
                    Feather.setVisible(false);
                    GameOverText.setVisible(false);
                    cmGUI.setVisible(true);
                    setVisible(false);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MapGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
        }};
        gameOverTransitionThread.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Feather;
    private javax.swing.JLabel GameOverBackground;
    private javax.swing.JLabel GameOverText;
    private javax.swing.JLayeredPane LevelTransition;
    // End of variables declaration//GEN-END:variables
}
